export default Object.freeze({
    INCREMENT: "INCREMENT",
    DECREMENT: "DECREMENT",

    FETCH_CLASSROOMS_REQUEST: "FETCH_CLASSROOMS_REQUEST",
    FETCH_CLASSROOMS_SUCCESS: "FETCH_CLASSROOMS_SUCCESS",
    FETCH_CLASSROOMS_FAIL: "FETCH_CLASSROOMS_FAIL",

    FETCH_TEACHERS_REQUEST: "FETCH_TEACHERS_REQUEST",
    FETCH_TEACHERS_SUCCESS: "FETCH_TEACHERS_SUCCESS",
    FETCH_TEACHERS_FAIL: "FETCH_TEACHERS_FAIL",

    FETCH_TEACHERS_LOAD_REQUEST: "FETCH_TEACHERS_LOAD_REQUEST",
    FETCH_TEACHERS_LOAD_SUCCESS: "FETCH_TEACHERS_LOAD_SUCCESS",
    FETCH_TEACHERS_LOAD_FAIL: "FETCH_TEACHERS_LOAD_FAIL",

    FETCH_FILTER_TEACHERS_REQUEST: "FETCH_FILTER_TEACHERS_REQUEST",
    FETCH_FILTER_TEACHERS_SUCCESS: "FETCH_FILTER_TEACHERS_SUCCESS",
    FETCH_FILTER_TEACHERS_FAIL: "FETCH_FILTER_TEACHERS_FAIL",

    FETCH_SUBJECTS_REQUEST: "FETCH_SUBJECTS_REQUEST",
    FETCH_SUBJECTS_SUCCESS: "FETCH_SUBJECTS_SUCCESS",
    FETCH_SUBJECTS_FAIL: "FETCH_SUBJECTS_FAIL",

    FETCH_TEACHER_CLASSROOMS_REQUEST: 'FETCH_TEACHER_CLASSROOMS_REQUEST',
    FETCH_TEACHER_CLASSROOMS_SUCCESS: 'FETCH_TEACHER_CLASSROOMS_SUCCESS',
    FETCH_TEACHER_CLASSROOMS_FAIL: 'FETCH_TEACHER_CLASSROOMS_FAIL',

    FETCH_TEACHER_GROUPS_REQUEST: 'FETCH_TEACHER_GROUPS_REQUEST',
    FETCH_TEACHER_GROUPS_SUCCESS: 'FETCH_TEACHER_GROUPS_SUCCESS',
    FETCH_TEACHER_GROUPS_FAIL: 'FETCH_TEACHER_GROUPS_FAIL',

    FETCH_FILTER_SUBJECTS_REQUEST: "FETCH_FILTER_SUBJECTS_REQUEST",
    FETCH_FILTER_SUBJECTS_SUCCESS: "FETCH_FILTER_SUBJECTS_SUCCESS",
    FETCH_FILTER_SUBJECTS_FAIL: "FETCH_FILTER_SUBJECTS_FAIL",

    FETCH_EMPTY_CLASSROOMS_REQUEST: "FETCH_EMPTY_CLASSROOMS_REQUEST",
    FETCH_EMPTY_CLASSROOMS_SUCCESS: "FETCH_EMPTY_CLASSROOMS_SUCCESS",
    FETCH_EMPTY_CLASSROOMS_FAIL: "FETCH_EMPTY_CLASSROOMS_FAIL",
});
