export default Object.freeze({
    INCREMENT: "INCREMENT",
    DECREMENT: "DECREMENT",

    FETCH_CLASSROOMS_REQUEST: "FETCH_CLASSROOMS_REQUEST",
    FETCH_CLASSROOMS_SUCCESS: "FETCH_CLASSROOMS_SUCCESS",
    FETCH_CLASSROOMS_FAIL: "FETCH_CLASSROOMS_FAIL",

    FETCH_TEACHERS_REQUEST: "FETCH_TEACHERS_REQUEST",
    FETCH_TEACHERS_SUCCESS: "FETCH_TEACHERS_SUCCESS",
    FETCH_TEACHERS_FAIL: "FETCH_TEACHERS_FAIL",

    FETCH_TEACHERS_LOAD_REQUEST: "FETCH_TEACHERS_LOAD_REQUEST",
    FETCH_TEACHERS_LOAD_SUCCESS: "FETCH_TEACHERS_LOAD_SUCCESS",
    FETCH_TEACHERS_LOAD_FAIL: "FETCH_TEACHERS_LOAD_FAIL",

    FETCH_SUBJECTS_REQUEST: "FETCH_SUBJECTS_REQUEST",
    FETCH_SUBJECTS_SUCCESS: "FETCH_SUBJECTS_SUCCESS",
    FETCH_SUBJECTS_FAIL: "FETCH_SUBJECTS_FAIL",
});
